### ISSUE TITLE
尝试部署了一下但是显示文件缺失

### ISSUE THREAD

**Issue by 123de234** [GuoYuefei/SyncPlayer#11]
<img width="388" alt="屏幕截图 2022-10-13 235816" src="https://user-images.githubusercontent.com/23733252/195646674-a8334a76-0532-4935-bd6e-0aa04ae6fcbf.png">

**Comment by GuoYuefei** [comment]
> <img alt="屏幕截图 2022-10-13 235816" width="388" src="https://user-images.githubusercontent.com/23733252/195646674-a8334a76-0532-4935-bd6e-0aa04ae6fcbf.png">

https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one
https://blog.csdn.net/weixin_40533355/article/details/81135112

应该是yarn的版本太低，这两个文档都指出了这个问题

**Comment by GuoYuefei** [comment]
记得应该环境中安装好golang编译环境、nodejs、yarn安装器；同时76379a7908368fdaefbc2698bbb895e2760aba4c中已修复高版本node修改加密算法引起的错误
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
